13.Docker.Lading/project/project/apps/authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('', views.AuthorsIndex.as_view(), name='index'),
    # path('create/', views.create, name='create')
    path('create/', views.AuthorsCreate.as_view(), name='create')
]

13.Docker.Lading/project/project/apps/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index_page, name='index'),
    path('articles/', views.articles, name='articles')
]

13.Docker.Lading/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.apps.homepage.urls')),
    path('authors/', include('project.apps.authors.urls'))
]

13.Docker.Lading/project/project/apps/authors/models.py
from django.db import models


class Author(models.Model):

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    LEVELS = (
        ('J', 'Junior'),
        ('M', 'Middle'),
        ('S', 'Senior'),
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(null=True)
    level = models.CharField(max_length=1, choices=LEVELS)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

13.Docker.Lading/project/project/apps/homepage/models.py
from django.db import models

# Create your models here.

13.Docker.Lading/project/project/apps/authors/forms.py
from django import forms
from .models import Author


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ('first_name', 'last_name', 'email', 'level')

13.Docker.Lading/project/project/apps/authors/views.py
from django.shortcuts import render,redirect, reverse
from django.views.generic import TemplateView
from django.views.generic import ListView
from .models import Author
from .forms import AuthorForm

class AuthorsIndex(ListView):

    model = Author
    context_object_name = 'authors'

    template_name = 'authors/index.html'

    # def get_queryset(self):
    #     return super().get_queryset().filter(email__endswith='com')

# def create(request):
#     return render(request, 'authors/create.html')

class AuthorsCreate(TemplateView):

    template_name = 'authors/create.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AuthorForm()
        return context
    
    def post(self, request):
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authors:index')  

        return render(request, self.template_name, {'form': form})

13.Docker.Lading/project/project/apps/homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index_page(request):
    #return HttpResponse('<h1>WELCOME TO INDEX OF HOMEPAGE!!!</h1>')
    return render(request, 'homepage/index.html')

def articles(request):
    #return HttpResponse('Articles', content_type='text/html')
    args = {
        'numbers_of_articles': list(range(1, 8))
    }
    return render(request, 'homepage/articles.html', args)

13.Docker.Lading/project/project/templates/authors/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <title>
  {% block title %}
      Base
  {% endblock %}
    </title>


  </head>
  <body>
    <br>
    <div class="container">

      {% block body %}
      {% endblock %}

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

13.Docker.Lading/project/project/templates/authors/create.html
{% extends 'authors/base.html' %}

{% block title %}
    Create author
{% endblock %}

{% block body %}
    <h3>Create a new author:</h3><br>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

13.Docker.Lading/project/project/templates/authors/index.html
{% extends "authors/base.html" %}

{% block title %}
    Index of authors
{% endblock %}

{% load email_domain %}
{% load random_joke %}
{% block body %}
    <h1>Welcome to page of authors</h1>
    <hr>
        {% joke %}
    <hr>
    <div>
        <ul class="list-group">
          {% for author in authors %}
            <li class="list-group-item list-group-item-secondary">
                {{ author.id }}. {{ author }} | {{ author.email|domain }}
            </li>
          {% empty %}
            <h4>Soory, no authors!</h4>
          {% endfor %}
        </ul>
    </div>
    <hr>
    <a href="{% url 'authors:create' %}"><h5>Create new author</h5></a>
{% endblock %}

13.Docker.Lading/project/project/templates/homepage/articles.html
{% extends 'homepage/base.html' %}

{% block title %}
Articles
{% endblock %}

{% block body %}
<h3>Welcome to articles!</h3>
<br>
<ul class="list-group">
  {% for num in numbers_of_articles %}
  {% cycle 'primary' 'secondary' as theme silent%}
    <li class="list-group-item list-group-item-{{theme}}">Article №{{ num }}</li>
  {% empty %}
    <h4>Soory, no articles!</h4>
  {% endfor %}



  {% comment %}
  <li class="list-group-item">Dapibus ac facilisis in</li>
  <li class="list-group-item list-group-item-primary">A simple primary list group item</li>
  <li class="list-group-item list-group-item-secondary">A simple secondary list group item</li>
  <li class="list-group-item list-group-item-success">A simple success list group item</li>
  <li class="list-group-item list-group-item-danger">A simple danger list group item</li>
  <li class="list-group-item list-group-item-warning">A simple warning list group item</li>
  <li class="list-group-item list-group-item-info">A simple info list group item</li>
  <li class="list-group-item list-group-item-light">A simple light list group item</li>
  <li class="list-group-item list-group-item-dark">A simple dark list group item</li>
  {% endcomment %}
</ul>
{% endblock %}

13.Docker.Lading/project/project/templates/homepage/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
  {% block title %}
  {% endblock %}
    </title>
  </head>
  <body>
    <br>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'authors:index' %}">Authors</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
        </div>
      </nav>
      <br>
      {% block body %}
      {% endblock %}
      <hr>
      <a href="{% url 'homepage:articles' %}">Visit to articles</a>
      <br>
      <a href="{% url 'homepage:index' %}">Visit to index</a>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

13.Docker.Lading/project/project/templates/homepage/index.html
{% extends 'homepage/base.html' %}

{% block title %}
Index page
{% endblock %}

{% block body %}
<h1>Welcome to index of homepage!!!</h1>
<div class="alert alert-primary" role="alert">
  A simple primary alert—check it out!
</div>
<div class="alert alert-secondary" role="alert">
  A simple secondary alert—check it out!
</div>
<div class="alert alert-success" role="alert">
  A simple success alert—check it out!
</div>
<div class="alert alert-danger" role="alert">
  A simple danger alert—check it out!
</div>
<div class="alert alert-warning" role="alert">
  A simple warning alert—check it out!
</div>
<div class="alert alert-info" role="alert">
  A simple info alert—check it out!
</div>
<div class="alert alert-light" role="alert">
  A simple light alert—check it out!
</div>
<div class="alert alert-dark" role="alert">
  A simple dark alert—check it out!
</div>
{% endblock %}